---
title: "Ethiopia Norms and values"
format: html
---

This dataset is available on the world values survey
[repository](https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp) as open
source.

```{r}
#| message: false
library(dplyr)

```

```{r}
#| message: false
# WVS_Cross-National_Inverted_Wave_7_csv_v5_0.csv
wvs <- readr::read_csv(here::here("data/wvs.csv"))

```

```{r}


# Ethiopia wvs 
eth_wvs <- wvs |> 
  filter(B_COUNTRY_ALPHA == "ETH") |> 
  select(B_COUNTRY_ALPHA, 
         # C_COW_ALPHA, 
         # Q_MODE, 
         N_REGION_ISO, 
         N_TOWN,
         G_TOWNSIZE,
         G_TOWNSIZE2, 
         H_SETTLEMENT, 
         H_URBRURAL,
         # I_PSU, 
         O1_LONGITUDE, 
         O2_LATITUDE,
         S_INTLANGUAGE, 
         Q177:Q195)

```

```{r}
# Cleaning data 
# Languages from the wolrd value survey manual
# Tigre => 4270, 
# Amharic => 140, 
# Oromifa => 3390, 
# English => 1240

eth_wvs <- eth_wvs |> 
  mutate(Language = case_when(
    S_INTLANGUAGE == 140 ~ "Amharic",
    S_INTLANGUAGE == 4270 ~ "Tigre",
    S_INTLANGUAGE == 3390 ~ "Oromifa",
    S_INTLANGUAGE == 1240 ~ "English")) |>
  mutate(region = case_when(
    N_REGION_ISO == 231001 ~ "Addis Ababa",
    N_REGION_ISO == 231002 ~ "Dire Dawa",
    N_REGION_ISO == 231003 ~ "Afar",
    N_REGION_ISO == 231004 ~ "Amhara",
    N_REGION_ISO == 231005 ~ "Benshangul-Gumaz",
    N_REGION_ISO == 231006 ~ "Gambela Peoples",
    N_REGION_ISO == 231007 ~ "Harari People",
    N_REGION_ISO == 231008 ~ "Oromia",
    N_REGION_ISO == 231009 ~ "Somali",
    N_REGION_ISO == 231010 ~ "Tigrai",
    N_REGION_ISO == 231011 ~ "SNNP")) |>
  mutate(town = case_when(
   N_TOWN == 231001 ~ "Adama Town - Wereda",
N_TOWN == 231002 ~ "Adama - Wereda",
N_TOWN == 231003 ~ "Arsi Negele - Wereda",
N_TOWN == 231004 ~ "Asayita - Wereda",
N_TOWN == 231005 ~ "Asosa - Wereda",
N_TOWN == 231006 ~ "Atsbi Wonberta -Rural",
N_TOWN == 231007 ~ "Awubere - Wereda",
N_TOWN == 231008 ~ "Babile - Wereda",
N_TOWN == 231009 ~ "Bahir Dar Zuriya - Wereda",
N_TOWN == 231010 ~ "Bahir Dar – Town - Wereda",
N_TOWN == 231011 ~ "Bensa - Wereda",
N_TOWN == 231012 ~ "Berahile - Wereda - Rural",
N_TOWN == 231013 ~ "Berbere- Wereda",
N_TOWN == 231014 ~ "Bereh - Wereda",
N_TOWN == 231015 ~ "Boloso Sore - Wereda",
N_TOWN == 231016 ~ "Burayu Town - Wereda",
N_TOWN == 231017 ~ "Chere - Wereda",
N_TOWN == 231018 ~ "Dale - Wereda",
N_TOWN == 231019 ~ "Damot Sore - Wereda",
N_TOWN == 231020 ~ "Dawa Chefa - Wereda",
N_TOWN == 231021 ~ "Debay Tilatgin - Wereda",
N_TOWN == 231022 ~ "Debub Mekele Town - Wereda",
N_TOWN == 231023 ~ "Dedo- Wereda",
N_TOWN == 231024 ~ "Desse Town - Wereda",
N_TOWN == 231025 ~ "Dibate - Wereda",
N_TOWN == 231026 ~ "Dire Dawa-Urban",
N_TOWN == 231027 ~ "Etang Special - Wereda",
N_TOWN == 231028 ~ "Fedis - Wereda",
N_TOWN == 231029 ~ "Fentale - Wereda",
N_TOWN == 231030 ~ "Gambella Zuriya- Wereda",
N_TOWN == 231031 ~ "Gedeb - Wereda",
N_TOWN == 231032 ~ "Gidan - Wereda",
N_TOWN == 231033 ~ "Ginir - Wereda",
N_TOWN == 231034 ~ "Godare - Wereda",
N_TOWN == 231035 ~ "Golina - Wereda -Rural",
N_TOWN == 231036 ~ "Gololcha - Wereda",
N_TOWN == 231037 ~ "Gonder Town - Wereda",
N_TOWN == 231038 ~ "Gozamin - Wereda",
N_TOWN == 231039 ~ "Guangua - Wereda",
N_TOWN == 231040 ~ "Gursum - Wereda",
N_TOWN == 231041 ~ "Habru - Wereda",
N_TOWN == 231042 ~ "Harari",
N_TOWN == 231043 ~ "Harshin - Wereda",
N_TOWN == 231044 ~ "Hawassa - City administation",
N_TOWN == 231045 ~ "Hintalo Wajirat-RURAL",
N_TOWN == 231046 ~ "Hitosa - Wereda",
N_TOWN == 231047 ~ "Homosha - Wereda",
N_TOWN == 231048 ~ "Hulet ej enese - Wereda",
N_TOWN == 231049 ~ "Jama - Wereda",
N_TOWN == 231050 ~ "Jijiga - Wereda",
N_TOWN == 231051 ~ "Kebele 01/05",
N_TOWN == 231052 ~ "Kebele 04",
N_TOWN == 231053 ~ "Kebele 07/08/09",
N_TOWN == 231054 ~ "Kebele 10/11",
N_TOWN == 231055 ~ "Kebele 14/15",
N_TOWN == 231056 ~ "Kebele 15/16",
N_TOWN == 231057 ~ "Kebele 16/17/18",
N_TOWN == 231058 ~ "Kebele 20/21",
N_TOWN == 231059 ~ "KebriI Beyah me",
N_TOWN == 231060 ~ "Kobo - Wereda",
N_TOWN == 231061 ~ "Kombolcha - Wereda",
N_TOWN == 231062 ~ "Konaba - Wereda - Rural",
N_TOWN == 231063 ~ "Konso Special - Wereda",
N_TOWN == 231064 ~ "Kutaber - Wereda",
N_TOWN == 231065 ~ "Laulay Maychew -Rural",
N_TOWN == 231066 ~ "Lasta - Wereda",
N_TOWN == 231067 ~ "Mao Komo Special - Wereda",
N_TOWN == 231068 ~ "Mecha- Wereda",
N_TOWN == 231069 ~ "Meda Welabu - Wereda",
N_TOWN == 231070 ~ "Menz Gera Midir - Wereda",
N_TOWN == 231071 ~ "Merti - Wereda",
N_TOWN == 231072 ~ "Mulo - Wereda",
N_TOWN == 231073 ~ "Omonada - Wereda",
N_TOWN == 231074 ~ "Pawe Special - Wereda",
N_TOWN == 231075 ~ "Raya Azebo-Rural",
N_TOWN == 231076 ~ "Saesi Tsadamba - Rural",
N_TOWN == 231077 ~ "Semen Achefer - Wereda",
N_TOWN == 231078 ~ "Setema - Wereda",
N_TOWN == 231079 ~ "Shinile - Wereda",
N_TOWN == 231080 ~ "Shire Enidaslase Town-Wereda",
N_TOWN == 231081 ~ "Sigmo - Wereda",
N_TOWN == 231082 ~ "Siraro - Wereda",
N_TOWN == 231083 ~ "Sodo Town - Wereda",
N_TOWN == 231084 ~ "Sululta - Wereda",
N_TOWN == 231085 ~ "Tulo- Wereda",
N_TOWN == 231086 ~ "Wendo Genet - Wereda",
N_TOWN == 231087 ~ "Were Lehe - Rural",
N_TOWN == 231088 ~ "Yalo - Wereda - Rural",
N_TOWN == 231089 ~ "Babile (Erer) - Wereda" )) |> 
  mutate(town_size_pop = case_when(
    G_TOWNSIZE == 1~ "Under 2k",
  G_TOWNSIZE == 2 ~ "2k-5k",
  G_TOWNSIZE == 3~ "5k-10k",
  G_TOWNSIZE == 4~ "10k-20k",
  G_TOWNSIZE == 5~ "20k-50k",
  G_TOWNSIZE == 6~ "50k-100k",
  G_TOWNSIZE == 7~ "100k-500k",
  G_TOWNSIZE == 8~ "500k +",
  G_TOWNSIZE == -5~ "No answer; Missing",
  G_TOWNSIZE == -4~ "Not asked in survey"
  )) |>
  mutate(town_size2_pop = case_when(
    G_TOWNSIZE2 == 1 ~ "Under 5,000",
    G_TOWNSIZE2 == 2 ~ "5000-20000",
    G_TOWNSIZE2 == 3 ~ "20000-100000",
    G_TOWNSIZE2 == 4 ~ "100000-500000",
    G_TOWNSIZE2 == 5 ~ "500000 and more",
    G_TOWNSIZE2 == -5 ~ "- No answer; Missing",
    G_TOWNSIZE2 == -4 ~ "- Not asked"
    )) |> 
  mutate(settelment_type = case_when(
  H_SETTLEMENT == 1 ~ "Capital city",
  H_SETTLEMENT == 2 ~ "Regional center",
  H_SETTLEMENT == 3 ~ "District center",
  H_SETTLEMENT == 4 ~ "Another city",
  H_SETTLEMENT == 5 ~ "Village",
  H_SETTLEMENT == -4 ~ "Not asked",
  H_SETTLEMENT == -5 ~ "No answer; Missing",
  )) |>
  mutate(resident_type = case_when(
    H_URBRURAL == 1 ~ "Urban",
    H_URBRURAL == 2 ~ "Rural",
    H_URBRURAL == -5 ~ "No answer; Missing",
    H_URBRURAL == -4  ~ "Not asked"
  ))
```


```{r}
eth_wvs |> 
  
```

